var express = require("express"),
    mongoose = require("mongoose");

var eventSchema = new mongoose.Schema({
	celebName:   String,
	bgImage:     String,
    tourName:    String,
    tourDates:   [{type: String}],
    tourCity:    [{type: String}],
    tourCountry: [{type: String}], 
    tourVenue:   [{type: String}],
    uploads: [
        {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Upload"
    }
]
});

var Event = mongoose.model("Event", eventSchema);
module.exports  = Event;

// Event.create({ celebName:"Boyce Avenue",  bgImage:"bg-images/babg.jpg", tourName:"2019 Tour",           tourDates:["4 April 2019", "9 April 2019", "13 April 2019" , "4 April 2019", "17 April 2019", "18 April 2019", "21 April 2019", "23 April 2019", "26 April 2019", "29 April 2019"], tourCity:["Taoyuan", "Tokyo", "Kuala Lumpur", "Hong Kong", "Hong Kong", "Incheon", "Osaka", "Singapore", "Bangkok", "Jakarta"], tourCountry:["Taiwan", "Japan", "Malaysia", "Hong Kong", "Hong Kong", "South Korea", "Japan", "Singapore", "Thailand", "Indonesia"], tourVenue:["Taoyuan City Stadium", "Tokyo Dome", "Bukit Jalil National Stadium", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Songdo Moonlight Festival Park", "Kyocera Dome", "Singapore National Stadium", "Rajamangala Stadium", "Gelora Bung Karno Stadium"]});
// Event.create({ celebName:"Ed Sheeran",    bgImage:"bg-images/es.jpg",   tourName:"Divide Tour",         tourDates:["4 April 2019", "9 April 2019", "13 April 2019" , "4 April 2019", "17 April 2019", "18 April 2019", "21 April 2019", "23 April 2019", "26 April 2019", "29 April 2019"], tourCity:["Taoyuan", "Tokyo", "Kuala Lumpur", "Hong Kong", "Hong Kong", "Incheon", "Osaka", "Singapore", "Bangkok", "Jakarta"], tourCountry:["Taiwan", "Japan", "Malaysia", "Hong Kong", "Hong Kong", "South Korea", "Japan", "Singapore", "Thailand", "Indonesia"], tourVenue:["Taoyuan City Stadium", "Tokyo Dome", "Bukit Jalil National Stadium", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Songdo Moonlight Festival Park", "Kyocera Dome", "Singapore National Stadium", "Rajamangala Stadium", "Gelora Bung Karno Stadium"]});
// Event.create({ celebName:"Ariana Grande", bgImage:"bg-images/ar.jpg",   tourName:"Sweetner World Tour", tourDates:["4 April 2019", "9 April 2019", "13 April 2019" , "4 April 2019", "17 April 2019", "18 April 2019", "21 April 2019", "23 April 2019", "26 April 2019", "29 April 2019"], tourCity:["Taoyuan", "Tokyo", "Kuala Lumpur", "Hong Kong", "Hong Kong", "Incheon", "Osaka", "Singapore", "Bangkok", "Jakarta"], tourCountry:["Taiwan", "Japan", "Malaysia", "Hong Kong", "Hong Kong", "South Korea", "Japan", "Singapore", "Thailand", "Indonesia"], tourVenue:["Taoyuan City Stadium", "Tokyo Dome", "Bukit Jalil National Stadium", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Songdo Moonlight Festival Park", "Kyocera Dome", "Singapore National Stadium", "Rajamangala Stadium", "Gelora Bung Karno Stadium"]});
// Event.create({ celebName:"Taylor Swift",  bgImage:"bg-images/ts.jpg",   tourName:"Reputation Tour",     tourDates:["4 April 2019", "9 April 2019", "13 April 2019" , "4 April 2019", "17 April 2019", "18 April 2019", "21 April 2019", "23 April 2019", "26 April 2019", "29 April 2019"], tourCity:["Taoyuan", "Tokyo", "Kuala Lumpur", "Hong Kong", "Hong Kong", "Incheon", "Osaka", "Singapore", "Bangkok", "Jakarta"], tourCountry:["Taiwan", "Japan", "Malaysia", "Hong Kong", "Hong Kong", "South Korea", "Japan", "Singapore", "Thailand", "Indonesia"], tourVenue:["Taoyuan City Stadium", "Tokyo Dome", "Bukit Jalil National Stadium", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Songdo Moonlight Festival Park", "Kyocera Dome", "Singapore National Stadium", "Rajamangala Stadium", "Gelora Bung Karno Stadium"]});
// Event.create({ celebName:"Charlie Puth",  bgImage:"bg-images/cp.jpg",   tourName:"Voice Notes Tour",    tourDates:["4 April 2019", "9 April 2019", "13 April 2019" , "4 April 2019", "17 April 2019", "18 April 2019", "21 April 2019", "23 April 2019", "26 April 2019", "29 April 2019"], tourCity:["Taoyuan", "Tokyo", "Kuala Lumpur", "Hong Kong", "Hong Kong", "Incheon", "Osaka", "Singapore", "Bangkok", "Jakarta"], tourCountry:["Taiwan", "Japan", "Malaysia", "Hong Kong", "Hong Kong", "South Korea", "Japan", "Singapore", "Thailand", "Indonesia"], tourVenue:["Taoyuan City Stadium", "Tokyo Dome", "Bukit Jalil National Stadium", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Songdo Moonlight Festival Park", "Kyocera Dome", "Singapore National Stadium", "Rajamangala Stadium", "Gelora Bung Karno Stadium"]});
// Event.create({ celebName:"Metallica",     bgImage:"bg-images/met.jpg",  tourName:"WorldWired Tour",     tourDates:["4 April 2019", "9 April 2019", "13 April 2019" , "4 April 2019", "17 April 2019", "18 April 2019", "21 April 2019", "23 April 2019", "26 April 2019", "29 April 2019"], tourCity:["Taoyuan", "Tokyo", "Kuala Lumpur", "Hong Kong", "Hong Kong", "Incheon", "Osaka", "Singapore", "Bangkok", "Jakarta"], tourCountry:["Taiwan", "Japan", "Malaysia", "Hong Kong", "Hong Kong", "South Korea", "Japan", "Singapore", "Thailand", "Indonesia"], tourVenue:["Taoyuan City Stadium", "Tokyo Dome", "Bukit Jalil National Stadium", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Songdo Moonlight Festival Park", "Kyocera Dome", "Singapore National Stadium", "Rajamangala Stadium", "Gelora Bung Karno Stadium"]});
// Event.create({ celebName:"Justin Bieber", bgImage:"bg-images/jb.jpg",   tourName:"Purpose Tour",        tourDates:["4 April 2019", "9 April 2019", "13 April 2019" , "4 April 2019", "17 April 2019", "18 April 2019", "21 April 2019", "23 April 2019", "26 April 2019", "29 April 2019"], tourCity:["Taoyuan", "Tokyo", "Kuala Lumpur", "Hong Kong", "Hong Kong", "Incheon", "Osaka", "Singapore", "Bangkok", "Jakarta"], tourCountry:["Taiwan", "Japan", "Malaysia", "Hong Kong", "Hong Kong", "South Korea", "Japan", "Singapore", "Thailand", "Indonesia"], tourVenue:["Taoyuan City Stadium", "Tokyo Dome", "Bukit Jalil National Stadium", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Songdo Moonlight Festival Park", "Kyocera Dome", "Singapore National Stadium", "Rajamangala Stadium", "Gelora Bung Karno Stadium"]});
// Event.create({ celebName:"Evanescence",   bgImage:"bg-images/ev.jpg",   tourName:"Synthesis Tour",      tourDates:["4 April 2019", "9 April 2019", "13 April 2019" , "4 April 2019", "17 April 2019", "18 April 2019", "21 April 2019", "23 April 2019", "26 April 2019", "29 April 2019"], tourCity:["Taoyuan", "Tokyo", "Kuala Lumpur", "Hong Kong", "Hong Kong", "Incheon", "Osaka", "Singapore", "Bangkok", "Jakarta"], tourCountry:["Taiwan", "Japan", "Malaysia", "Hong Kong", "Hong Kong", "South Korea", "Japan", "Singapore", "Thailand", "Indonesia"], tourVenue:["Taoyuan City Stadium", "Tokyo Dome", "Bukit Jalil National Stadium", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Fantasy Road Outdoor Venue Hong Kong Disneyland", "Songdo Moonlight Festival Park", "Kyocera Dome", "Singapore National Stadium", "Rajamangala Stadium", "Gelora Bung Karno Stadium"]});
